<ips:template parameters="$raids, $bosses, $diffTags, $id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />
<h1>Hello!</h1>
<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $form->error}}
		<div class="ipsMessage ipsMessage_error">
			{$form->error}
		</div>
	{{endif}}
	<div class="ipsPad">
		<ul class='ipsList_reset'>
        {{foreach $elements as $name => $contents}}
					<div id='ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' class="ipsTabs_panel ipsPad" aria-labelledby="{$id}_tab_{$name}" aria-hidden="false">
							<ul class='ipsForm ipsForm_vertical'>
								{{foreach $contents as $inputName => $input}}
                                    {$input|raw}
								{{endforeach}}
							</ul>
					</div>
				{{endforeach}}
		</ul>
	</div>
	<ul class="ipsPad ipsList_reset ipsClearfix">
		{{foreach $actionButtons as $button}}
			<li>{$button|raw}</li>
		{{endforeach}}
	</ul>
</form>