<ips:template parameters="$title, $discord" />

<h3 class='ipsType_reset ipsWidget_title'>
	{$title}
</h3>
<div class="recruitSidebar">
    <div class="recruit2">
        <div class="info-sidebar">
        <div class="info-sidebar-section">
            <div class="sidebar-section-header">
                <h1>Server Info</h1>
            </div>
            <div class="sidebar-section-content">
                <span>US - Arthas - Horde</span>
            </div>
        </div>

        <div class="info-sidebar-section">
            <div class="sidebar-section-header">
                <h1>Raid Schedule</h1>
            </div>
            <div class="sidebar-section-content">
                <p>Friday | 10pm - 1:30am EST</p>
                <p>Saturday | 10pm - 1:30am EST</p>
            </div>
        </div>

        <div class="info-sidebar-section">
            <div class="sidebar-section-header" id="discord-container">
                <a class="ipsButton ipsButton_medium ipsButton_important" href="{$discord}" rel="external nofollow" target="_blank">Faceroll Discord</a>
            </div>
        </div>
    </div>
  </div>
</div>